[package]
name = "rustzork"
version = "0.1.0"
authors = ["olson-dan <olson-dan@users.noreply.github.com>"]

[features]
default = ["cli"]
cli = ["clap"]

[dependencies]
clap = { version = "2.20.1", optional = true }
rand = { git = "https://github.com/rust-lang-nursery/rand" }